linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  gocritic:
     disabled-checks:
      - ifElseChain

linters:
  enable:
  - megacheck
  - govet
  - golint
  - gocyclo
  - gosec
  - unconvert
  - dupl
  - maligned
  - nakedret
  - prealloc
  - scopelint
  - gocritic