name: checks
on:
  workflow_dispatch:
    inputs:
      number:
        type: string
      token:
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: gh pr merge --admin --squash ${{ inputs.number }}
      env:
        GITHUB_TOKEN: ${{ secrets[inputs.token] }}
